### PR TITLE
Use forward slash in path

### PR DESCRIPTION
**Pull request by xDShot**
Otherwise it cannot import or export properly on Unix-like OSes

### CODE REVIEW

**Comment by SE2Dev** [comment]
Merged! I also added a path normalization step as well. Unfortunately, I don't have access to a Unix-like OS at the moment - so I don't have any way to check that the new code still works on Unix-like OSes. Can you please verify that import / export still work correctly, so that I can make a new release commit?

**Comment by xDShot** [comment]
Tried development branch. Unfortunately, not. For some reasons it drops latest slash before the file itself.

What done:
* Imported the mesh (smd format with Blender Source Tools)
* Selected Armature
* Imported wanted seanim

but it just created 1 frame action with only reference pose

The log from blender:
`SMD IMPORTER: now working on c_usa_cia_masonjr_armlaunch_viewhands_LOD0
- This is a mesh
- Imported 72 new bones
- Imported 1 frames of animation
DAG zero... not allowed to happen!
- New material: mtl_viewarm_watchglass
- Imported 72 polys
DAG zero... not allowed to happen!
- New material: mtl_t6_wpn_arm_launcher
- Imported 4138 polys
DAG zero... not allowed to happen!
- New material: mtl_viewarm_gen_datapad
- Imported 960 polys
DAG zero... not allowed to happen!
- New material: mtl_viewarm_usa_seal6_masonjr
- Imported 7917 polys
DAG zero... not allowed to happen!
- Imported 1931 polys
SMD c_usa_cia_masonjr_armlaunch_viewhands_LOD0 imported in 1 second 

Imported 1 files in 11.0 seconds
  (  0.0001 sec |   0.0001 sec) viewmodel_msmc_reload.seanim
Could not open file for reading:
 /home/xdshot/msmc/bo2/animsviewmodel_msmc_reload.seanim
  (  0.0135 sec |   0.0134 sec) Finished!
Progress: 100.00%`

**Comment by SE2Dev** [comment]
Ah yes - I see what's happening here. `os.path.normalize()` strips the trailing slash, and since I was just doing a simple string append operation, a new slash is never added. I'll switch to `os.path.join()` and see how that works.

**Comment by SE2Dev** [comment]
Ok, I modified the directory path logic in 91c1183. Can you confirm that it functions correctly?

**Comment by xDShot** [comment]
`Imported 1 files in 5.1 seconds
  (  0.0006 sec |   0.0004 sec) viewmodel_msmc_reload_empty.seanim
Could not open file for reading:
 /home/xdshot/msmc/bo2/anims\viewmodel_msmc_reload_empty.seanim
  (  0.0168 sec |   0.0167 sec) Finished!
Progress: 100.00%`

Backslash returned
¯\_(ツ)_/¯

**Comment by SE2Dev** [comment]
Ech - I guess os.path.join() is broken... Neat! I suppose I'll try normalizing the path *again* after joining the parts together. Out of curiosity which OS are you using?

**Comment by xDShot** [comment]
Linux (Arch Linux x64)

**Comment by SE2Dev** [comment]
Alright, let's try this again: 246e1d3

**Comment by xDShot** [comment]
Confirming it working :+1:

**Comment by SE2Dev** [comment]
Out of curiosity, is there any particular reason you're using the SMD versions of the models over the XMODEL_EXPORTS?

**Comment by xDShot** [comment]
Dunno ¯\\\_(ツ)\_/¯ Just wanted to import with preferred reliable tools. I'll try xmodel bit later.

**Pull request merged**
