### PR TITLE
Removed scale constant (Change in spec)

### PR DESCRIPTION
**Pull request by dtzxporter**
Removed scale constant in preparation for 'unitless mode'

### CODE REVIEW

**Comment by dtzxporter** [comment]
I mean remove the retarded blender conversion thing you do, Maya plugin already doesn't change the data

**Comment by SE2Dev** [comment]
So are we just going unitless in general or what?

**Comment by dtzxporter** [comment]
You need to transfer the scale shit to blender-cod (import/export) and remove it from io_scene_seanim, so that people using SEAnims in a non-cod context are allowed to import correctly.

**Comment by SE2Dev** [comment]
I already added scale support to Blender-CoD - unfortunately the way Blender implements scene-wide unit scaling makes things like this a bit *complicated*. Unless I remove all scaling code from both Blender-CoD and io_seanim, there's no way to gaurantee that an animation and model are currently using the same units.

**Comment by SE2Dev** [comment]
Even if I were to remove all scaling code from both, it *still* wouldn't necessarily ensure that a given seanim would import correctly on a model that was loaded using another importer that applies its own scale.

**Comment by dtzxporter** [comment]
Then you need to remove it from seanims at the minimum because it breaks compatibility with anything.

**Comment by dtzxporter** [comment]
Just drop it IMO

**Pull request closed without merging**
